### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by procmail** [srsgores/jquery-hash-tabs#4]
Hi,

Your Hash Tabs plugin looks wonderful, and I am wondering if Hash Tabs can:
1) have nested tabs within a tab (or tabs)?
2) Open to a specific tab when the page loads?

Thanks!

**Comment by srsgores** [comment]
1. No.
2. Yes.

**Comment by samhuntsocial** [comment]
easytabs supports nested tabs, although the author seemed to have stopped maintaining the code base.

**Comment by srsgores** [comment]
Nested tabs have poor usability.  Will not be implementing any time soon.

**Comment by samhuntsocial** [comment]
the nested tab does not have to be *visually* inside of the parent tab. it can just be *visually* underneath it. nowadays, with tabs that look like material design tabs, it's actually got a different usability feel to it. the tabs look lightweight to the user.

so, for material design tabs, you click a tab. below it shows 3 tabs. to the user, usability feels OK because the tabs are visually pretty light as it's just horizontal lines. to the developer, those are nested tabs. 

i think nested tabs with hash would be pretty sweet.

was just using mailchimp's app. they use nested tabs. and, unfortunately, no their nested tabs aren't hashed either.

**Comment by srsgores** [comment]
The only way this could ever work is with query parameters.  When I was designing this plugin, I had thought about implementing this feature, but reasoned that having such a feature would add unnecessary complications to the plugin initialization.

Perhaps you can make a pull request with query params as an initialization parameter, and we can see about merging in the feature; for now, I don't really see the point in nested tabs.

**Comment by samhuntsocial** [comment]
thanks. but i'm already using easytabs for my nested tabs (unfortunately, its hash for nested tabs doesn't work properly).
